/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import javax.swing.JCheckBox;
import vista.ButtonRenderer;
/**
 *
 * @author herna
 */
public class FrmListaProductos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmListaProductos.class.getName());

    /**
     * Creates new form FrmListaProductos
     */
    public FrmListaProductos() {
        initComponents();
        tblProductos.getColumnModel().getColumn(4).setCellRenderer(new ButtonRenderer());
        tblProductos.getColumnModel().getColumn(4).setCellEditor(new ButtonEditor(new JCheckBox()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelFiltros = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbSeccion = new javax.swing.JComboBox<>();
        cmbProveedor = new javax.swing.JComboBox<>();
        txtNombre = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        btnCrearNuevo = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        panelTabla = new javax.swing.JPanel();
        scrollTabla = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelHeader.setBackground(new java.awt.Color(0, 0, 153));
        panelHeader.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("EL JASWER DEL SOFWER");
        panelHeader.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, 400, 30));

        getContentPane().add(panelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 60));

        panelFiltros.setBackground(new java.awt.Color(245, 245, 245));
        panelFiltros.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelFiltros.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Sección");
        panelFiltros.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 15, 80, 20));

        jLabel3.setText("Proveedor: ");
        panelFiltros.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 15, 100, 20));

        jLabel4.setText("Código:");
        panelFiltros.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 15, 80, 20));

        jLabel5.setText("Nombre del Producto:");
        panelFiltros.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 15, 130, 20));

        cmbSeccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelFiltros.add(cmbSeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 35, 180, 30));

        cmbProveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelFiltros.add(cmbProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 35, 180, 30));
        panelFiltros.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 35, 180, 30));
        panelFiltros.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 35, 180, 30));

        btnCrearNuevo.setBackground(new java.awt.Color(0, 153, 0));
        btnCrearNuevo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCrearNuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearNuevo.setText("Crear Nuevo");
        panelFiltros.add(btnCrearNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 75, 120, 30));

        btnBuscar.setBackground(new java.awt.Color(0, 102, 204));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        panelFiltros.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 75, 100, 30));

        btnLimpiar.setBackground(new java.awt.Color(70, 70, 70));
        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("Limpiar");
        panelFiltros.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 75, 100, 30));

        getContentPane().add(panelFiltros, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 900, 110));

        panelTabla.setBackground(new java.awt.Color(255, 255, 255));
        panelTabla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelTabla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblProductos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Seccion", "Stcok", "Acción"
            }
        ));
        scrollTabla.setViewportView(tblProductos);

        panelTabla.add(scrollTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 880, 370));

        getContentPane().add(panelTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 900, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmListaProductos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCrearNuevo;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cmbProveedor;
    private javax.swing.JComboBox<String> cmbSeccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel panelFiltros;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelTabla;
    private javax.swing.JScrollPane scrollTabla;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
